/*
 * HelloWorld2.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using HelloWorld2.PCL.Controllers;
using HelloWorld2.PCL.Http.Client;
using HelloWorld2.PCL.Utilities;

namespace HelloWorld2.PCL
{
    public partial class HelloWorld2Client
    {

        /// <summary>
        /// Singleton access to Helloworld controller
        /// </summary>
        public HelloworldController Helloworld
        {
            get
            {
                return HelloworldController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public HelloWorld2Client() { }
        #endregion
    }
}