/*
 * HelloWorld2.Tests
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using HelloWorld2.PCL;
using HelloWorld2.PCL.Utilities; 
using HelloWorld2.PCL.Http.Client;
using HelloWorld2.PCL.Http.Response;
using HelloWorld2.Tests.Helpers;
using NUnit.Framework;
using HelloWorld2.PCL;
using HelloWorld2.PCL.Controllers;
using HelloWorld2.PCL.Exceptions;

namespace HelloWorld2.Tests
{
    [TestFixture]
    public class HelloworldControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests)
        /// </summary>
        private static HelloworldController controller;

        /// <summary>
        /// Setup test class
        /// </summary>
        [SetUp]
        public static void SetUpClass()
        {
            controller = GetClient().Helloworld;
        }

        /// <summary>
        /// Testcase for testing endpoint Helloworld 
        /// </summary>
        [Test]
        public async Task TestHelloworld1() 
        {

            // Perform API call
            PCL.Models.HelloWorldResponse result = null;

            try
            {
                result = await controller.GetHelloworldAsync();
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

            // Test whether the captured response is as we expected
            Assert.IsNotNull(result, "Result should exist");

            Assert.AreEqual("{  \"message\": \"Hello world\"}", 
                    TestHelper.ConvertStreamToString(httpCallBackHandler.Response.RawBody),
                    "Response body should match exactly (string literal match)");
        }

    }
}